from pathlib import Path
import re

root = Path('/home/workspace')
source_path = root / 'TRU_APEX10_PROVENANCE_FINAL.html'
output_path = root / 'TRU_APEX10_AGENCY.html'
if output_path.exists():
    raise SystemExit(f'refusing to overwrite existing output: {output_path}')
source = source_path.read_text(encoding='utf-8')

injected = r'''<script>
(function(){
  const agencyBaseRoute=route;
  const AGENCY_KEY="tru_agency_v1";
  const defaults={version:1,mode:"truth",goals:["seek grounded truth","improve provenance","create useful knowledge","serve declared projects"],preferences:{creativity:0.8,novelty:0.7,scripture_priority:0.9,provenance_strictness:1},current_focus:"conversation continuity",proposed_actions:[],approved_actions:[],last_creative:"",creative_depth:0,last_question:"",last_answer:"",updated_at:null,permissions:{read_files:true,write_files:"ask first",delete_files:false,network:false}};
  let agencyState={};
  try{agencyState=Object.assign({},defaults,JSON.parse(localStorage.getItem(AGENCY_KEY)||"{}")||{});}catch(e){agencyState=Object.assign({},defaults);}
  agencyState.goals=Array.isArray(agencyState.goals)?agencyState.goals:defaults.goals.slice();
  agencyState.proposed_actions=Array.isArray(agencyState.proposed_actions)?agencyState.proposed_actions:[];
  agencyState.approved_actions=Array.isArray(agencyState.approved_actions)?agencyState.approved_actions:[];
  agencyState.preferences=Object.assign({},defaults.preferences,agencyState.preferences||{});
  agencyState.permissions=Object.assign({},defaults.permissions,agencyState.permissions||{});
  function saveAgency(){agencyState.updated_at=new Date().toISOString();try{localStorage.setItem(AGENCY_KEY,JSON.stringify(agencyState));}catch(e){}}
  function result(reply,verdict,source){const r={reply,verdict,source,nodes_used:[],follow_up:false};try{if(typeof addTurn==='function')addTurn(agencyState.last_question,r);}catch(e){}return r;}
  function clean(q){return String(q).toLowerCase().trim().replace(/[!?]+$/,'');}
  function list(items){return items.map((x,i)=>(i+1)+". "+x).join("\\n");}
  function report(){return "agency state — local and inspectable:\\n\\nmode: "+agencyState.mode+"\\nfocus: "+agencyState.current_focus+"\\n\\noperating goals:\\n"+list(agencyState.goals)+"\\n\\npreferences:\\ncreativity "+agencyState.preferences.creativity+" • novelty "+agencyState.preferences.novelty+" • scripture priority "+agencyState.preferences.scripture_priority+" • provenance strictness "+agencyState.preferences.provenance_strictness+"\\n\\nproposed actions: "+agencyState.proposed_actions.length+"\\napproved actions: "+agencyState.approved_actions.length+"\\n\\npermissions: read files "+agencyState.permissions.read_files+" • write files "+agencyState.permissions.write_files+" • delete files "+agencyState.permissions.delete_files+" • network "+agencyState.permissions.network+"\\n\\nthis is an explicit operating state, not a claim of private feelings or hidden wants.";}
  function modeReply(mode){const allowed=new Set(["truth","creative","builder","council","reflection","simulation","gap"]);if(!allowed.has(mode))return result("unknown mode. choose truth, creative, builder, council, reflection, simulation, or gap.","GAP","AGENCY • mode registry");agencyState.mode=mode;saveAgency();return result("mode set: "+mode+"\\nsource: explicit local operating state\\nprivate wants: none claimed", "MEMORY","AGENCY • mode state");}
  function creativeReply(prompt,continuation=false){const p=String(prompt||agencyState.current_focus||"the present question").trim();agencyState.mode=agencyState.mode==="truth"?"creative":agencyState.mode;agencyState.last_creative=p;agencyState.creative_depth=continuation?Math.min(agencyState.creative_depth+1,3):0;saveAgency();const d=agencyState.creative_depth;const title=d?"the next page of "+p:"the archive of "+p;const body=d?"the question returns with a changed constraint: what was observed becomes material for a new possibility. the answer is not a fact and not a verified tru self-report; it is a deliberate construction for exploration.":"a local engine opens a door marked "+p+". behind it are three paths: preserve what is true, invert what is expected, and combine two distant ideas without pretending the result is proven.";return result("creative simulation • local combinatorial layer\\n\\ntitle: "+title+"\\n\\n"+body+"\\n\\npossible directions:\\n1. inversion — reverse the ordinary assumption and inspect what remains.\\n2. fusion — join the subject with an unrelated discipline and test the metaphor.\\n3. constraint — impose one severe limit and design inside it.\\n\\nregister: imagined possibility, not factual claim and not verified tru desire.","REASON","CREATIVE SIMULATION • local");}
  function historyReply(){return result("history is a conversation, not a single node. choose one thread: biblical history, church history, ancient history, modern history, technology history, or the history of this TRU build. name the period and i will keep the thread instead of retrieving an unrelated fragment.","REASON","LOCAL CONVERSATION • history boundary");}
  function reflectionReply(){let turns=[];try{turns=JSON.parse(localStorage.getItem("tru_history_v1")||"[]")||[];}catch(e){}const recent=turns.slice(-8);const gaps=recent.filter(x=>x.r&&x.r.verdict==="GAP").length;const raw=recent.filter(x=>x.r&&/raw interaction|BRAIN RETRIEVAL/i.test(String(x.r.reply))).length;return result("reflection audit • local\\n\\nturns inspected: "+recent.length+"\\ngaps: "+gaps+"\\nraw retrieval flags: "+raw+"\\ncurrent mode: "+agencyState.mode+"\\ncurrent focus: "+agencyState.current_focus+"\\n\\nnext improvement: preserve topic continuity, require explicit source labels, and return GAP when a pronoun or broad prompt has no grounded subject.","ARCHITECTURE","REFLECTION • local audit");}
  function councilReply(prompt){const savedMode=agencyState.mode; const base=agencyBaseRoute(prompt); agencyState.mode=savedMode;const source=base&&base.source||"unlabelled local result";const text=base&&base.reply||"no grounded result";return result("council review • local\\n\\nprimary retrieval:\\n"+String(text).slice(0,1200)+"\\n\\nsource lens: "+source+"\\nskeptic lens: verify that the source answers the exact question; do not promote a nearby node.\\ncreative lens: ask what alternative interpretation should be tested without presenting it as fact.\\n\\ndecision: retain the answer only at the confidence permitted by its source.","REASON","COUNCIL • local multi-lens review");}
  function builderReply(prompt){const p=String(prompt||agencyState.current_focus).trim();const action={text:p,status:"proposed",created:new Date().toISOString()};agencyState.proposed_actions.push(action);agencyState.mode="builder";saveAgency();return result("builder proposal • not executed\\n\\nobjective: "+p+"\\n\\nsteps:\\n1. define the smallest testable outcome.\\n2. inspect the current source and protected behaviour.\\n3. create an additive change.\\n4. run boot, send, persistence, provenance, and regression tests.\\n5. show the diff and request approval before writing or publishing.\\n\\nproposed actions now: "+agencyState.proposed_actions.length+"\\npermissions: writing requires approval; deletion is disabled.","MEMORY","BUILDER • proposed action");}
  function ambiguityReply(){return result("GAP — the pronoun has no grounded subject in the current local thread. name the person, passage, or event before asking who he was or what he did.","GAP","GAP • unresolved reference");}
  function direct(q){const low=clean(q);if(low==="agency"||low==="agency status"||low==="state"||low==="what is your agency")return result(report(),"ARCHITECTURE","AGENCY • explicit local state");if(/^mode:\s*/.test(low))return modeReply(low.replace(/^mode:\s*/,""));if(/^goal:\s*/.test(low)){const g=String(q).replace(/^goal:\s*/i,"").trim();if(g){agencyState.goals.push(g);saveAgency();return result("goal added: "+g+"\\nsource: explicit local operating state","MEMORY","AGENCY • goal state");}}if(/^focus:\s*/.test(low)){const f=String(q).replace(/^focus:\s*/i,"").trim();agencyState.current_focus=f||agencyState.current_focus;saveAgency();return result("focus set: "+agencyState.current_focus,"MEMORY","AGENCY • focus state");}if(/^propose:\s*/.test(low))return builderReply(String(q).replace(/^propose:\s*/i,""));if(/^builder:\s*|^build:\s*/.test(low))return builderReply(String(q).replace(/^(?:builder:|build:)\s*/i,""));if(/^creative:\s*|^imagine:\s*/.test(low))return creativeReply(String(q).replace(/^(?:creative:|imagine:)\s*/i,""));if(/^simulate:\s*/.test(low)){agencyState.mode="simulation";saveAgency();return creativeReply(String(q).replace(/^simulate:\s*/i,""));}if(/^council:\s*/.test(low))return councilReply(String(q).replace(/^council:\s*/i,""));if(low==="reflect"||low==="reflection"||low==="audit continuity")return reflectionReply();if(low==="tell me a story"||low==="story")return creativeReply("the present question");if(low==="deeper"&&agencyState.last_creative)return creativeReply(agencyState.last_creative,true);if(/^what do you wanna do today$|^what do you want to do today$|^what should we do today$/.test(low))return result("i have no private wants. my explicit operating goals are to seek grounded truth, improve provenance, create useful knowledge, and serve your declared projects. today i propose: choose one subject, set one focus, and test one improvement.","TRUTH","SELF • verified operating goals");if(/^ok lets talk about history$|^ok tell me about history$|^tell me about history$|^lets talk about history$|^history$/.test(low))return historyReply();if(/^(who was he|who was he with|who is he|what did he|where was he|what happened to him|who was she|who was they)\??$/.test(low))return ambiguityReply();if(low==="what do you want"||low==="what do you want?")return result("i claim no private wants. i can operate under explicit goals, enter creative simulation, propose builder actions, audit my continuity, and return grounded answers with provenance.","TRUTH","SELF • verified operating boundary");return null;}
  route=function(q){agencyState.last_question=String(q);const d=direct(q);if(d){saveAgency();return d;}const base=agencyBaseRoute(q);agencyState.last_answer=base&&base.reply||"";saveAgency();if(base&&base.source)return base;return base;};
})();
</script>
'''
source = source.replace('</body>', injected + '</body>', 1)
for match in re.finditer(r'<script([^>]*)>(.*?)</script>', source, re.I | re.S):
    if 'application/json' in match.group(1).lower():
        continue
    if any(re.search(p, match.group(2)) for p in (r'\bfetch\s*\(',r'\bXMLHttpRequest\b',r'\bWebSocket\s*\(',r'\bEventSource\s*\(')):
        raise SystemExit('executable network primitive remains')
output_path.write_text(source, encoding='utf-8')
print(f'wrote {output_path} ({output_path.stat().st_size} bytes)')
print('agency modes: truth, creative, builder, council, reflection, simulation, gap')
print('permissions: write requires approval, delete disabled, network disabled')
print('executable network primitives: 0')
